### ISSUE TITLE
Mongo Queries returning empty

### ISSUE THREAD

**Issue by gakuba** [bbonnin/zeppelin-mongodb-interpreter#1]
I am doing something like
%mongodb
db.test.find({}).table()  but all I get is nothing. the test collection has some data in it.

**Comment by gakuba** [comment]
It is working. the issue was that the interpretor works with incubator zeppelin only. I could not get it working with official apache zeppelin.

**Comment by bbonnin** [comment]
Thanks for reporting this issue. I will fix it in the following days.
Which version of Zeppelin are you using ?

**Comment by gakuba** [comment]
Zeppelin-0.6.0.

I will have a second look and see if I messed up somewhere in the process. it does work well though for incubator versions.

**Comment by gakuba** [comment]
Hi Bruno,

I found the issue. it is working. I did a fresh mvn package but I had to do a few tweaks
- Changed `<groupId>org.apache.zeppelin</groupId>
  <artifactId>zeppelin-mongodb</artifactId>
  <packaging>jar</packaging>
  <version>0.6.0</version>
  <name>Zeppelin: MongoDB interpreter</name>
  <url>http://www.apache.org</url>`
- Added then had to add the module to the main pom.xml of zeppelin project. like this `<module>zeppelin-mongodb-interpreter</module>` inside the `<modules></modules>` tags

**Comment by bbonnin** [comment]
ok, thank you!

**Comment by treselleqa** [comment]
Cannot run program "mongo" (in directory "."): CreateProcess error=2, The system cannot find the file specified
Hi, while running mongodb in zeppelin  I'm facing above issue, please help.

**Comment by bbonnin** [comment]
I think you should take a look at the issue #4 . It looks like you have not "mongo" in your path and you must update the property `mongo.shell.path`.

**Comment by treselleqa** [comment]
We can connect to local mongodb, but when executing %mongodb there is no result but we have data in mongodb

![zep_screenshot](https://cloud.githubusercontent.com/assets/23230751/19958112/8001319c-a1c2-11e6-96f6-ca5993abd5ed.png)

![mongodb_screenshot](https://cloud.githubusercontent.com/assets/23230751/19958118/94297f62-a1c2-11e6-9662-d3b64c051209.png)

 INFO [2016-11-03 11:45:02,433]({pool-2-thread-2} SchedulerFactory.java[jobStarted]:131) - Job remoteInterpretJob_1478153702431 started by scheduler mongo
 INFO [2016-11-03 11:45:02,760]({pool-2-thread-2} SchedulerFactory.java[jobFinished]:137) - Job remoteInterpretJob_1478153702431 finished by scheduler mongo

**Comment by bbonnin** [comment]
Can you try something like this:

```
%mongodb
var db = db.getSiblingDB('your database name')
db.restaurants.find().table()
```

`table` is a method for formating your data to be able to be read by Zeppelin.

**Comment by treselleqa** [comment]
hi there? can u help with this issue
![mongo](https://cloud.githubusercontent.com/assets/23230751/19964518/28a9af2a-a1e8-11e6-8c5c-0d0a3f0241a0.png)

**Comment by treselleqa** [comment]
Interpreter settings are 
![interpreter](https://cloud.githubusercontent.com/assets/23230751/19964584/8a297032-a1e8-11e6-95e3-bab3d684a109.png)

**Comment by bbonnin** [comment]
Have you tried connect to your database with your mongo shell (outside zeppelin) ?
This problem with hotfix is not due zeppelin or the interpreter, there is something wrong with your installation. See http://stackoverflow.com/questions/29316482/mongo-error-on-i-control-hotfix
The `%mongodb` must be the first line.

**Comment by treselleqa** [comment]
hi, it worked :+1: Can you tell me how to merge all the notebooks in zeppelin, because seperate notebooks are creating confusion. I have notebook 1, notebook2, don't know how to merge.

**Comment by bbonnin** [comment]
Sorry, I don't think there is such a function in Zeppelin. You should merge yourself by doing copy/paste of the code in your notebooks (you can have several paragraphs in one note).

**Comment by treselleqa** [comment]
So I need to open notebooks in notepad, and copy paste other notebook code in this?

**Comment by bbonnin** [comment]
Maybe, you should use the zeppelin UI (in your browser), open the different notes in differents tabs, and copy/paste your code.

**Comment by treselleqa** [comment]
can you tell me how?

**Comment by treselleqa** [comment]
copy paste the code in a html page using embed code feature in zeppelin paragraph?

**Comment by mikehao** [comment]
I have Zeppelin 0.7 installed, and after installed MongoDB interpreter by following the instruction, i got f following error in Zeppelin UI. What could be wrong?

paragraph_1494473680860_234684658's Interpreter mongodb not found
org.apache.zeppelin.interpreter.InterpreterException: paragraph_1494473680860_234684658's Interpreter mongodb not found
	at org.apache.zeppelin.notebook.Note.run(Note.java:605)
	at org.apache.zeppelin.socket.NotebookServer.persistAndExecuteSingleParagraph(NotebookServer.java:1641)
	at org.apache.zeppelin.socket.NotebookServer.runParagraph(NotebookServer.java:1615)
	at org.apache.zeppelin.socket.NotebookServer.onMessage(NotebookServer.java:265)
	at org.apache.zeppelin.socket.NotebookSocket.onWebSocketText(NotebookSocket.java:59)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:65)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:161)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:632)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:480)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
