### ISSUE TITLE
Mongodb-interpreter failing with V0.7.3

### ISSUE THREAD

**Issue by thealy** [bbonnin/zeppelin-mongodb-interpreter#13]
I recently upgraded my Zeppelin install to 0.7.3 and basically made a mess of it. I've got it back running again for Spark, and managed to add back another "external" Interpreter. But so far I am unable to get the interpreter running for mongodb. I believe I installed it the same way as last time. I have tried rebuilding the code, which builds without error, as well as downloading the .jar directly.

I added zeppelin-mongodb-0.7.0.jar as my only artifact, and I can see it present in the corresponding local-repo directory.

The configuration of the interpreter is this: (May be attached file if image does not insert here)

![zepp-mongo](https://user-images.githubusercontent.com/706792/30990768-7acddb9c-a470-11e7-82b7-ed69ed97c0ba.png)

My most basic test was just this, with %mongodb and %spark as the bound interpreters:

%mongodb
use test;

The error result is:
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.valueOf(Long.java:803)
	at org.apache.zeppelin.shell.ShellInterpreter.interpret(ShellInterpreter.java:91)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:97)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:498)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Can you confirm that 0.7.3 is working OK for you and offer any suggestions?

Also, I got the same exact error when using this code block:
import com.mongodb.spark.config.ReadConfig
import com.mongodb.spark.sql._

val config = sqlContext.sparkContext.getConf
.set("spark.mongodb.keep_alive_ms", "15000")
.set("spark.mongodb.input.uri", "mongodb://mongo1.sec.bnl.local:27017")
.set("spark.mongodb.input.database", "test")
.set("spark.mongodb.input.collection", "zips")
//todo https://docs.mongodb.com/spark-connector/configuration/
.set("spark.mongodb.input.readPreference.name", "primaryPreferred")
.set("spark.mongodb.input.partitioner", "MongoSamplePartitioner")
.set("spark.mongodb.input.partitionerOptions.partitionSizeMB", "1024")
val readConfig = ReadConfig(config)
val zips = sqlContext.read
.format("com.mongodb.spark.sql")
.mongo(readConfig)
println("zips Schema:")
zips.printSchema()
zips.show(1)

**Comment by bbonnin** [comment]
Hello

I was not able yet to test Zeppelin 0.7.3 ;-(

Just one remark, instead of using `use <db>`, you have to use `db = db.getSiblingDB('<db>')`

Take a look at: https://docs.mongodb.com/manual/tutorial/write-scripts-for-the-mongo-shell/
It explains the difference between the interactive shell and the content of a script.

I am going to test 0.7.3...

**Comment by thealy** [comment]
Salut Bruno, and thanks for your prompt reply. I really appreciate the work of skilled people like you who contribute such tools that help all of us.
And thanks for your link and correction to the test code.

**Comment by bbonnin** [comment]
I tested with 0.7.3 and it worked.

But there is something strange with your configuration: in the last version of the interpreter, I have added new parameters for the security (authent database) and I don't see them in your snapshots.
Are you sure you have the last version ?

Here my config:

![image](https://user-images.githubusercontent.com/1908593/31020986-c61f10ce-a534-11e7-90cd-195bc98967a1.png)

**Comment by thealy** [comment]
I edited my config to add mongo.server.authentdatabase (with blank value) and restarted the interpreter. But the result is the same. I will try a seperate net install in my user space instead of /usr/share/ and test further from there. 
Thanks for your help.

**Comment by thealy** [comment]
I failed with the config above (except server is not on localhost) even after falling back to a complete re-install of Zeppelin in a new directory. I tried an assortment of commands because I was not sure of exact format:

%mongodb
db = db.getSiblingDB('<test>')

%mongodb
conn = new Mongo();
db = conn.getDB("test");

Here is the error it produces:
org.apache.thrift.TApplicationException: Internal error processing getFormType
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client.recv_getFormType(RemoteInterpreterService.java:337)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client.getFormType(RemoteInterpreterService.java:323)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.getFormType(RemoteInterpreter.java:446)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.getFormType(LazyOpenInterpreter.java:111)
	at org.apache.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:387)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.RemoteScheduler$JobRunner.run(RemoteScheduler.java:329)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I suspect I'm doing something very stupid, but I can't find it.

**Comment by thealy** [comment]
Hi Bruno.
Here is the resulting section from my interpreter.json file after configuration. Can you see anything wrong that might suggest the cause of my problem? The group setting of file or HDFS does not seem right to me, but there was no option to create a new group when I created the interpreter. 

Thanks,
Terry

    "2CWWUH194": {
      "id": "2CWWUH194",
      "name": "mongodb",
      "group": "file",
      "properties": {
        "mongo.shell.path": "/home/thealy/Downloads/zeppelin-0.7.3-bin-netinst/bin/mongo",
        "mongo.server.username": "",
        "mongo.server.host": "mongo1.sec.bnl.local",
        "zeppelin.interpreter.localRepo": "/home/thealy/Downloads/zeppelin-0.7.3-bin-netinst/local-repo/2CWWUH194",
        "mongo.server.port": "27017",
        "mongo.shell.command.timeout": "60000",
        "mongo.server.database": "test",
        "mongo.shell.command.table.limit": "1000",
        "mongo.server.authentdatabase": "",
        "zeppelin.interpreter.output.limit": "102400"
      },
      "status": "READY",
      "interpreterGroup": [
        {
          "name": "hdfs",
          "class": "org.apache.zeppelin.file.HDFSFileInterpreter",
          "defaultInterpreter": false,
          "editor": {
            "editOnDblClick": false
          }
        }
      ],
      "dependencies": [
        {
          "groupArtifactVersion": "/home/thealy/Downloads/zeppelin-mongodb-interpreter/target/zeppelin-mongodb-0.7.0.jar",
          "local": false
        }
      ],
      "option": {
        "remote": true,
        "port": -1,
        "perNote": "shared",
        "perUser": "shared",
        "isExistingProcess": false,
        "setPermission": false,
        "users": [],
        "isUserImpersonate": false
      }
    },

**Comment by thealy** [comment]
Hi Bruno-
I finally got it. The group creation seemed to be the problem. After adding it and re-defining the Interpreter, it is now connecting. Sorry to waste your time, and thanks again for making this interpreter available - it is key for my use of Zeppelin.
-Terry
