### ISSUE TITLE
windows got errors 

### ISSUE THREAD

**Issue by xtuyaowu** [bbonnin/zeppelin-mongodb-interpreter#16]
hi got such errors ,need help thanks!
java.io.IOException: Cannot run program "D:\Program" (in directory "."): CreateProcess error=2, system can not find the file
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)

**Comment by bbonnin** [comment]
Hello,
It looks like you have white spaces in a path (mongo path ?).
As a quick fix, you should move (or copy) your mongodb installation to a path without spaces in the name.
