### ISSUE TITLE
zeppelin 0.9.0 support ?

### ISSUE THREAD

**Issue by yanngv29** [bbonnin/zeppelin-mongodb-interpreter#28]
while testing zeppelin 0.9.0, i try mongodb interpreter but i got this error : 
org.apache.zeppelin.interpreter.InterpreterException: java.io.IOException: Interpreter process is not running
Interpreter launch command:  java -Dfile.encoding=UTF-8 -Dlog4j.configuration=file:///Users/toto/dev/zeppelin/zeppelin-0.9.0-preview1-bin-netinst/conf/log4j.properties -Dzeppelin.log.file='/Users/toto/dev/zeppelin/zeppelin-0.9.0-preview1-bin-netinst/logs/zeppelin-interpreter-mongodb-shared_process-toto-mbp-2.home.log' -Xms1024m -Xmx2048m -XX:MaxPermSize=512m -cp "::/Users/toto/dev/zeppelin/zeppelin-0.9.0-preview1-bin-netinst/interpreter/zeppelin-interpreter-shaded-0.9.0-preview1.jar" org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer 192.168.1.30 65488 "mongodb-shared_process" :
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer.<clinit>(RemoteInterpreterServer.java:112)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.open(RemoteInterpreter.java:134)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.getFormType(RemoteInterpreter.java:298)
	at org.apache.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:431)
	at org.apache.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:74)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:130)
	at org.apache.zeppelin.scheduler.RemoteScheduler$JobRunner.run(RemoteScheduler.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Interpreter process is not running
Interpreter launch command:  java -Dfile.encoding=UTF-8 -Dlog4j.configuration=file:///Users/toto/dev/zeppelin/zeppelin-0.9.0-preview1-bin-netinst/conf/log4j.properties -Dzeppelin.log.file='/Users/toto/dev/zeppelin/zeppelin-0.9.0-preview1-bin-netinst/logs/zeppelin-interpreter-mongodb-shared_process-toto-mbp-2.home.log' -Xms1024m -Xmx2048m -XX:MaxPermSize=512m -cp "::/Users/toto/dev/zeppelin/zeppelin-0.9.0-preview1-bin-netinst/interpreter/zeppelin-interpreter-shaded-0.9.0-preview1.jar" org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer 192.168.1.30 65488 "mongodb-shared_process" :
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer.<clinit>(RemoteInterpreterServer.java:112)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.internal_create(RemoteInterpreter.java:166)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.open(RemoteInterpreter.java:131)
	... 12 more

**Comment by bbonnin** [comment]
Hello,
It seems that a slf4j lib is missing (Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory)
Have you tried other interpreters ?
The mongodb interpreter depends on zeppelin-interpreter that has slf4j as a dependency.

**Comment by yanngv29** [comment]
Sorry for the delay. 
I give a new try to zeppelin 0.9.0 but i have the same problem. 
I try python interpreter : it's working 
i try md interpreter : it's also working.

**Comment by yanngv29** [comment]
in classpath there is no log4j or slf4j or ....

-cp ":/home/toto/zeppelin-0.9.0-preview1-bin-netinst/interpreter/mongodb/*::/home/toto/zeppelin-0.9.0-preview1-bin-netinst/interpreter/zeppelin-interpreter-shaded-0.9.0-preview1.jar"

**Comment by yanngv29** [comment]
i solved the problem by adding all those dependencies in the interpreter config panel : 

org.slf4j:slf4j-log4j12:1.7.10	
commons-logging:commons-logging:1.1.1	
log4j:log4j:1.2.17	
org.apache.commons:commons-exec:1.3	
commons-lang:commons-lang:2.5	
commons-io:commons-io:2.4

**Comment by brunobonnin** [comment]
Thank for your fix !
But, that's weird... 
Maybe something has changed in Zeppelin 0.9.0, I have to update this interpreter.
